formspree_form_id: formspree_form_id
name: Jonez
title: Jonez Blog
description: Il blog ufficiale di Gabriel Jones, scoprimi e esplora i miei
  interessi, e le mie ricerche
tags:
  - blog
  - bambini
  - formazione
  - informatica
  - netflix
  - politica
  - lifestyle
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: info@18f.it
disqus_username: ""
