backend:
  name: git-gateway
  branch: "48891"

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "staff"
    label: "Staff"
    folder: "content/staff"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "usr" }
      - { label: "Titolo Pagina", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }

      - label: "Informazioni Personali"
        name: "person"
        widget: "object"
        fields:
          - { label: "Nome", name: "name", widget: "string" }
          - { label: "Immagine Copertina", name: "image", widget: "image" }
          - { label: "Incarico", name: "incarico", widget: "string" }
          - { label: "Tipo di Incarico", name: "tipo_incarico", widget: "string"}
          - { label: "Data di Insediamento", name: "data_insediamento", widget: "datetime", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY", time_format: false }
          - { label: "Email", name: "email", widget: "string" }
          - label: "Competenze"
            name: "competenze"
            widget: "list"
            summary: "{{fields}}"
            field: { label: "Competenza", name: "item", widget: "string" }

          - label: "Organizzazioni"
            name: "organizzazione"
            widget: "list"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "text" }

          - label: "Documenti"
            name: "documents"
            widget: "list"
            fields:
              - { label: "Titolo", name: "title", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "string" }
              - { label: "Link al Documento", name: "link", widget: "string" }

      - { label: "Contenuto", name: "body", widget: "markdown" }
  - name: "pagine_it"
    label: "Pagine"
    folder: "content/it"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { name: "title", label: "Titolo", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime", default: "", hidden: true }
      - { name: "permalink", label: "Link personalizzato", widget: "string", required: true }
      - { name: "body", label: "page", widget: "markdown" }
  - name: "articoli"
    label: "Articoli"
    folder: "content/articoli"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titolo", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime", default: "", hidden: true }
      - { name: "link", label: "Link personalizzato", widget: "string", required: false }
      - { name: "body", label: "Contenuto", widget: "markdown" }
  - name: "progetti"
    label: "Progetti"
    folder: "content/progetti"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Nome", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime", default: "", hidden: true }
      - { name: "site", label: "Sito del progetto", widget: "string", required: false }
      - { name: "founder", label: "Fondatore", widget: "string" }
      - { name: "director", label: "Dirigente", widget: "string" }
      - { name: "director_link", label: "Link al profilo del dirigente", widget: "string", required: false }
      - { name: "document", label: "Documento", widget: "file", media_library: { allow_multiple: false } }
      - { name: "body", label: "Descrizione", widget: "markdown" }
  - name: "documenti"
    label: "Documenti"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    preview_path: "docs/{{slug}}/"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "doc" }
      - { label: "Descrizione", name: "descrizione", widget: "text" }
      - { label: "Tipo di documento", name: "tipo_documento", widget: "string" }
      - { label: "Link al tipo di documento", name: "tipo_documento_link", widget: "string" }
      - { label: "Nome documento", name: "documento_nome", widget: "string" }
      - { label: "Link al documento", name: "documento_link", widget: "string" }
      - { label: "Peso documento", name: "documento_peso", widget: "string" }
      - { label: "Redattore - Nome", name: "redattore_nome", widget: "string" }
      - { label: "Redattore - Link", name: "redattore_link", widget: "string" }
      - { label: "Redattore - Descrizione", name: "redattore_descrizione", widget: "text", required: false }
      - { label: "Formati disponibili", name: "formati", widget: "string" }
      - { label: "Licenza", name: "licenza", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", default: "/docs/{{slug}}/" }
  - name: "organizzazioni"
    label: "Organizzazioni"
    folder: "content/organizzazioni"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    preview_path: "organizzazioni/{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "organi" }
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", default: "/organizzazioni/{{slug}}/", required: true }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Competenze", name: "competenze", widget: "markdown" }
      - { label: "Tipologia di organizzazione", name: "tipologia", widget: "string" }
      - label: "Responsabile"
        name: "responsabile"
        widget: "object"
        fields:
          - { label: "Nome", name: "responsabile_nome", widget: "string" }
          - { label: "Ruolo", name: "responsabile_ruolo", widget: "string" }
          - { label: "URL", name: "responsabile_url", widget: "string", required: false }
      - label: "Sede principale"
        name: "sede"
        widget: "object"
        fields:
          - { label: "Nome", name: "sede_nome", widget: "string" }
          - { label: "Indirizzo", name: "sede_indirizzo", widget: "string" }
          - { label: "URL", name: "sede_url", widget: "string", required: false }
      - { label: "Telefono", name: "telefono", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Ulteriori informazioni", name: "more_info", widget: "markdown" }
  - name: "albo"          # Nome interno (deve corrispondere a _albo)
    label: "Albo Pretorio"  # Etichetta che vedi nell’interfaccia CMS
    folder: "content/albo"        # Cartella dove salvare i file markdown
    create: true           # Permetti la creazione di nuovi documenti
    slug: "{{slug}}"       # Nome file basato sul titolo slugificato
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Tipo Documento", name: "tipo", widget: "select", options: ["Delibera", "Determina", "Avviso", "comunicazione", "Verbali", "Altro"] }
      - { label: "File PDF", name: "file", widget: "file", allow_multiple: true, media_library: /assets/docs/ }
      - { label: "Descrizione", name: "description", widget: "text", required: false }
