[build]
  base = ""
  publish = "_site"
  command = "bundle exec jekyll build"

[context.production.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 200
